version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
    - texlive-publishers
    - libmagickwand-dev
    - ghostscript
  jobs:
    post_system_dependencies:
      - sudo sed -i '/disable ghostscript format types/,+6d' /etc/ImageMagick-6/policy.xml

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
